name: Automate Script

on:
  schedule:
    - cron:  '0 * * * *'
  push:
    branches:
    - master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: { ref: master } 
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Get new data
        env: 
            DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
            INGATLAN_APP_SECRET: ${{ secrets.INGATLAN_APP_SECRET }}
        run: |
          inv upload-new-data